spring:
  application:
    name: blog

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: joon
    password: 1234
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul

